### PR TITLE
Massive Damage

### PR DESCRIPTION
**Pull request by drkekyll**
I'm not sure why, but the idea of massive damage suddenly filled me with joy, so I did this. I didn't actually add to `ENUM_RAW_PrintTable` because it looks like you're keeping them in alphabetical order, but I wasn't sure what adjusting the numbers assigned to those would do elsewhere.

### CODE REVIEW

**Comment by drkekyll** [comment]
In retrospect, it could probably be applied only to player characters since, generally, they're the only ones who will be downed rather than killed when they take their remaining HP in damage. I also didn't see anything in RAW about anything being immune to massive damage, but it seems like it would be reasonable to add.

**Comment by FelipeRenault** [comment]
Loved it 😆 
But there's always risk in allowing that into NPCs. Maybe there are some fights where it's somehow scripted the target doesn't die I'm thinking mainly about the fight at the end of Act 2
<details>
<summary>Spoiler</summary>

Where Ketheric dies first, but there's a cutscene for him to transform into the Avatar of Myrkul. Insta-killing him might cause issues, so we should test this first before allowing NPCs to have that
</details>

**Comment by drkekyll** [comment]
Totally fair! I still need to play through the game so i can keep those things in mind.

If the relevant NPCs are flagged somehow (like the Luring Song victim in the druid grove is tagged) we could exclude them, but without a comprehensive list that could be tough. I can adjust it to only add to players and origin characters fairly easily if you want though.

**Comment by FelipeRenault** [comment]
Given the specificity of enemies which this change would actually affect (mainly ones with undead fortitude), I think it's worth not including enemies at all to avoid potential bugs

**Comment by drkekyll** [comment]
Yeah, that makes sense.

**Comment by FelipeRenault** [comment]
Decided to change the name to `Instant Death` to avoid confusion with the Massive Damage optional rules from DMG p.273
Also made it enabled by default because it's a base rule, not an optional one, and whoever gets instagibbed, `D E S E R V E D  I T`

**Pull request merged**
